name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: SonarQube Scan
        run: |
          ./gradlew sonarqube  # Adjust this command based on your build tool (e.g., Maven: mvn sonar:sonar)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
